### ISSUE TITLE
Redis backend, cannot release lock

### ISSUE THREAD

**Issue by ipartola** [Xavier-Lam/django-cache-lock#2]
Using a Redis backend, there is an error when the lock gets released:

`AttributeError: type object 'Lock' has no attribute 'LUA_RELEASE_SCRIPT'`

I can't find any other mention of this `LUA_RELEASE_SCRIPT` in the code.

**Comment by Xavier-Lam** [comment]
LUA_RELEASE_SCRIPT is defined at here:
https://github.com/andymccurdy/redis-py/blob/e57daf554d6a4a66373de6605d13fb7a185852e9/redis/lock.py#L24

I have imported the `Lock` class of redis-py at [line 251](https://github.com/Xavier-Lam/django-cache-lock/blob/796047f86bbab5fe5b7b03770f3d0408e4812a2b/django_lock.py#L251), I don't know why you got this error, you can check out if [the Lock class here](https://github.com/Xavier-Lam/django-cache-lock/blob/796047f86bbab5fe5b7b03770f3d0408e4812a2b/django_lock.py#L267) is reference to the `redis.lock.Lock` correctly.

Sorry for my poor English.
