### ISSUE TITLE
What happens if a process holding a lock exits abnormally?

### ISSUE THREAD

**Issue by stevecj** [Xavier-Lam/django-cache-lock#3]
What happens if a process holding a lock exits abnormally?

Can we have something in the README text about that?

**Comment by Xavier-Lam** [comment]
If an exception raised in the context you've locked, the lock will released automatically when you exited from the context.
If you killed the process or the power of the server suddenly off, the lock may release after the `timeout` seconds you have set when you acquire the lock. By default, this value is `None`, if it is `None`, the lock will be hold forever, and you need to release this lock manually.
My English is not very well, I'm afraid I couldn't write a good readme file to explain how it works.
